services:
  - type: web
    name: yfapp-backend
    env: python
    region: singapore
    buildCommand: |
      # Python setup
      python -m pip install --upgrade pip
      cd backend
      pip install -r requirements.txt --no-cache-dir
    startCommand: cd backend && gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/backend