services:
  - type: web
    name: yfapp-backend
    env: python
    buildCommand: |
      cd backend
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: PORT
        value: "10000"