# filepath: /c:/Users/user/yfapp/backend/render.yaml
services:
  - type: web
    name: yfapp-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: PORT
        value: "10000"

